version: '3.6'

services:
  redis:
    container_name: screener_redis
    image: redislabs/redistimeseries:latest
    networks:
      - screener_network

  screener:
    container_name: screener_worker
    image: zwastler/crypto_screener:latest
    build:
      context: ..
      dockerfile: deployment/Dockerfile
    env_file:
      - ../.env
    networks:
      - screener_network

networks:
  screener_network:
    driver: bridge